# Generated by Django 5.2.1 on 2025-06-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="gender",
            field=models.BooleanField(default=False),
        ),
    ]
